[package]
name    = "web"
version = "0.1.0"
authors = ["Alex Burka <aburka@seas.upenn.edu>"]

[profile.release]
debug = true

[features]
nightly = [
    "comms/nightly",
    "utils/nightly",
    "teensy/nightly",
    "lazy_static/nightly",
    ]

[dependencies] 
comms                = { path = "../../back/comms"     }
utils                = { path = "../../utils"          }
teensy               = { path = "../../drivers/teensy" }
guilt-by-association = "0.2"
lazy_static          = { git = "https://github.com/durka/lazy-static.rs", branch = "internal-unstable" }
notify               = "2.4"
time                 = "0.1"
uuid                 = "0.1"
log                  = "0.3"

# iron deps
iron                 = "0.2"
handlebars-iron      = "0.9"
handlebars           = "0.11"
staticfile           = { version = "0.0.6", default-features = false }
mount                = "0.0.9"
hyper                = "0.7"
router               = "0.0.15"
urlencoded           = "0.2"
url                  = "0.5"
rustc-serialize      = "0.3" # TODO migrate to serde
websocket            = "0.14"
