[package]
name    = "web"
version = "0.1.0"
authors = ["Alex Burka <aburka@seas.upenn.edu>"]

[profile.release]
debug = true

[features]
nightly = [
    "comms/nightly",
    "utils/nightly",
    "teensy/nightly",
    "lazy_static/nightly",
    ]

[dependencies] 
comms                = { path = "../../back/comms"     }
utils                = { path = "../../utils"          }
flow                 = { path = "../../back/flow"      }
teensy               = { path = "../../drivers/teensy" }
guilt-by-association = "0.2"
lazy_static          = "0.2"
log                  = "0.3"

# iron deps
iron                 = "0.3"
handlebars-iron      = "0.15"
handlebars           = "0.16"
staticfile           = { version = "0.2", default-features = false }
mount                = "0.1"
hyper                = "0.8"
router               = "0.1"
urlencoded           = "0.3"
url                  = "0.5"
rustc-serialize      = "0.3" # TODO migrate to serde
websocket            = "0.16"
