[package]
name = "nri"
version = "0.1.0"
authors = ["Alex Burka <aburka@seas.upenn.edu>"]
build = "build.rs"
exclude = ["src/web/templates/*", "src/web/bootstrap/*"] # TODO take this out before packaging

[profile.dev]
opt-level = 3
debug = true

[dependencies]
log = "*"
env_logger = "*"
libc = "*"
time = "*"
image = "*"
hprof = "*"

# iron deps
iron = "*"
handlebars-iron = "*"
staticfile = { version = "*", default-features = false }
mount = "*"
hyper = "0.5.2"
router = "*"
rustc-serialize = "*"
websocket = "*"

[dependencies.guilt-by-association]
git = "git://github.com/durka/guilt-by-association"

