[package]
name = "nri"
version = "0.1.0"
authors = ["Alex Burka <aburka@seas.upenn.edu>"]
build = "build.rs"
exclude = ["src/web/templates/*", "src/web/bootstrap/*"] # TODO take this out before packaging

[profile.dev]
opt-level = 3
debug = true

[features]
default = ["watch"]
watch = ["handlebars-iron/watch"]

[dependencies]
log = "*"
env_logger = "*"
libc = "*"
#lazy_static = "*"
time = "*"
chrono = "*"
image = "*"
hprof = "*"
#ioctl-rs = "*"
num = "*"
enum_primitive = "*"
serial = "*"
csv = "*"
uuid = "*"

# stuff that I wrote
guilt-by-association = "*"

# iron deps
iron = "*"
handlebars-iron = "*"
staticfile = { version = "*", default-features = false }
mount = "*"
hyper = "*"
router = "*"
rustc-serialize = "*"
websocket = "*"

#[dependencies.guilt-by-association]
#path = "/Users/alex/Programming/rust/guilt-by-association"

#[dependencies.websocket] # take this out once reem bumps iron to hyper 0.6
#git = "git://github.com/haptics-nri/rust-websocket"

#[dependencies.ioctl-rs]
#git = "git://github.com/haptics-nri/ioctl-rs"
#branch = "usbdevfs"

[dependencies.lodepng] # waiting for cargo publish
git = "git://github.com/durka/lodepng-rust"
branch = "stabilize"

[dependencies.lazy_static] # waiting for cargo publish
git = "git://github.com/kimundi/lazy-static.rs"

