[package]
name = "nri"
version = "0.1.0"
authors = ["Alex Burka <aburka@seas.upenn.edu>"]
build = "build.rs"

[dependencies]
log = "0.3"
env_logger = "0.3"
libc = "0.1.8"
time = "0.1"
csv = "0.14.2"

