[package]
name = "nri"
version = "0.1.0"
authors = ["Alex Burka <aburka@seas.upenn.edu>"]
build = "build.rs"
exclude = ["src/web/templates/*", "src/web/bootstrap/*", "src/web/flows/*", "data/*", "keepalive"] # TODO take this out before packaging

[profile.dev]
opt-level = 3
debug = true

[features]
nightly = []

[dependencies]
log = "0.3"
env_logger = "0.3"
libc = "0.2"
lazy_static = "0.1"
custom_derive = "0.1"
conv = "0.3"
time = "0.1"
chrono = "0.2"
image = "0.4"
hprof = "0.1"
serial = "0.3"
csv = "0.14"
uuid = "0.1"
abort_on_panic = "1.0"
notify = "2.4"

# stuff that I wrote
guilt-by-association = "0.2"

# iron deps
iron = "0.2"
handlebars-iron = "0.9"
handlebars = "0.11"
staticfile = { version = "0.0.6", default-features = false }
mount = "0.0.9"
hyper = "0.6"
router = "0.0.15"
urlencoded = "0.2"
url = "0.2"
rustc-serialize = "0.3" # TODO migrate to serde
websocket = "0.13"

