[package]
name = "nri"
version = "0.1.0"
authors = ["Alex Burka <aburka@seas.upenn.edu>"]
build = "build.rs"
exclude = ["src/web/templates/*", "src/web/bootstrap/*"] # TODO take this out before packaging

[dependencies]
log = "0.3"
env_logger = "0.3"
libc = "0.1.8"
time = "0.1"

iron = "0.1.18"
handlebars-iron = "0.6.5"
staticfile = { version = "0.0.2", default-features = false }
mount = "0.0.7"
hyper = "0.5.2"

