[package]
name    = "flow"
version = "0.1.0"
authors = ["Alex Burka <aburka@seas.upenn.edu>"]

[profile.release]
debug = true

[features]
nightly = [
    "comms/nightly",
    "teensy/nightly",
    "utils/nightly",
    "lazy_static/nightly",
    ]

[dependencies]
utils                = { path = "../../utils"          }
comms                = { path = "../comms"             }
teensy               = { path = "../../drivers/teensy" }
lazy_static          = "0.2"
chrono               = "0.3"
uuid                 = "0.2"
rustc-serialize      = "0.3" # TODO migrate to serde

