[package]
name    = "scribe"
version = "0.1.0"
authors = ["Alex Burka <aburka@seas.upenn.edu>"]

[profile.dev]
opt-level = 3
debug     = true

[dependencies]
utils          = { path = "../../utils" }
libc           = "0.2"
lazy_static    = "0.1"
abort_on_panic = "1.0"

